3D SPECFEM GF implementation
uafgeotools/mtuq pull request #218
Opened 2023-07-25 23:11 UTC by ammcpherson

As discussed in [Issue 203](https://github.com/uafgeotools/mtuq/issues/203), I have implemented using 3D Green's Functions for force generated in SPECFEM3D. There are no major changes to existing code, and the implementation was similar to that of the 3D Green's Functions for moment tensors generated in SPECFEM3D. 

The filename convention for the GFs reflects that for the FORCESOLUTION file in SPECFEM3D, you give the east, north, and vertical components of force.

2023-07-27 05:15 UTC, rmodrak commented
Amanda, thank you.  I am hoping the CI tests will be fixed soon.

2023-07-27 22:34 UTC, rmodrak requested changes
Amanda,
I've tried making  a slight change to avoid overwriting the moment tensor extensions with the force extensions.
Could you please test out the attached and add to the pull request?
thank you,
[SPECFEM3D_SAC.py.txt](https://github.com/uafgeotools/mtuq/files/12188631/SPECFEM3D_SAC.py.txt)

Ryan

2023-08-01 19:38 UTC, ammcpherson commented
Ryan,

Your changes yield the same results, so I have added them to my branch and pull request.

Thanks!
-Amanda

2023-08-02 09:13 UTC, rmodrak approved these changes

2023-08-02 09:13 UTC, merged